title: Cameron Kemske's Portfolio
description: Cameron Kemske's Portfolio Page. Housing Cameron's various projects from university and self-study experiences. 
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cameron Scott Kemske 
author-img: profile-headshot-new.png
about-author: Please click the posts on the right panel to access each project catergory. Use my profile picture above to return to this main page. Thank you! 
social-linkedin: /cameronkemske/
social-email: cameronkemske@gmail.com

# Disqus
discus-identifier: mr-kemske # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
