title: Cameron Kemske's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/ckemske46.github.io" # the subpath of your site, e.g. /blog
url: "ckemske46.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cameron Scott Kemske 
author-img: profile-headshot-new.png
about-author: Please click the posts on the right panel to access each project catergory. Use my profile picture above to return to this main page. Wish to contact me? Please use the links below. Thank you!
social-linkedin: /cameronkemske/
social-email: cameronkemske@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
